# JAGT1806/repo-actions/.github/actions/set-version-maven
name: "Set Version Maven"
description: "Set Maven Version (pom.xml)"

inputs:
  version:
    required: true
    description: Maven Version to update
  commit_message:
    required: false
    description: Commit message to change version
    default: "chore: set version to ${{ inputs.version }}"
  github_token:
    required: true
    description: Github Token

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        mvn -q -DnewVersion=${{ inputs.version }} versions:set versions:commit || {
          # fallback to sed for multi-module
          find . -name pom.xml -exec sed -i "0,/<version>.*<\/version>/s//<version>${{ inputs.version }}<\/version>/" {} \;
        }
        
        git add -A
        git commit -m "${{ inputs.commit_message }}" || echo "no changes"