# JAGT1806/repo-actions/.github/actions/create-release-gh
name: Create GitHub Release

inputs:
  tag:
    required: true
    description: Tag to create Github release
  title:
    required: false
    description: Title to create Github release
    default: "${{ inputs.tag }}"
  notes:
    required: false
    description: Text to watch
  draft:
    required: false
    description: Draft
    default: "false"
  prerelease:
    required: false
    description: prerelease
    default: "false"
  github_token:
    required: true
    description: Github Token

runs:
  using: composite
  steps:
    - name: Normalize tag
      id: norm
      shell: bash
      run: |
        TAG="${{ inputs.tag }}"
        if [[ "$TAG" != v* ]]; then
          TAG="v$TAG"
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    - name: Create GitHub Release
      shell: bash
      run: |
        gh release create "${{ inputs.tag }}" --title "${{ inputs.title }}" --notes "${{ inputs.notes }}" $( [ "${{ inputs.draft }}" == "true ] && echo "--draft" ) $( [ "${{ inputs.prerelease }}" == "true" ] && echo "--prerelease )
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}