# JAGT1806/repo-actions/.github/actions/create-release-branch
name: Create Release Branch
description: Create release branch from develop and set non-SNAPSHOT version

inputs:
  version:
    required: false
    description: Version without snapshot (auto-detected if not provided)
  version_scheme:
    required: false
    description: Version bump scheme if version not provided (major, minor, patch)
    default: minor
  base_branch:
    required: false
    description: Base branch for release
    default: develop
  github_token:
    required: true
    description: Github Token
outputs:
  release_branch:
    description: Created release branch name
    value: ${{ steps.create.outputs.release_brach }}
  release_version:
    description: Release version set
    value: ${{ steps.create.outputs.release_version }}
  base_version:
    description: Base version from develop
    value: ${{ steps.create.outputs.base_version }}

runs:
  using: composite
  steps:
    - name: Auto-detect version if not provided
      id: detect-version
      if: ${{ inputs.version == '' }}
      uses: JAGT1806/repo-actions/.github/actions/detect-release-version@main
      with:
        develop_branch: ${{ inputs.base_branch }}
        version_scheme: ${{ inputs.version_scheme }}

    - name: Create release branch and set version
      id: create
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        set -euo pipefail
        
        if [ -n "${{ inputs.version }}" ]; then
          VERSION="${{ inputs.version }}"
          BASE_VERSION="${VERSION%.*}.0"
        else
          VERSION="${{ steps.detect-version.outputs.release_version }}"
          BASE_VERSION="${{ steps.detect-version.outputs.base_version }}"
        fi
        
        BASE_BRANCH="${{ inputs.base_branch }}"
        RELEASE_BRANCH="release/${VERSION%.*}"
        
        echo "Creating release branch: $RELEASE_BRANCH"
        echo "Release version: $VERSION"
        echo "Base version: $BASE_VERSION"
        
        # Ensure base branch is up-to-date
        git fetch origin
        git checkout "$BASE_BRANCH"
        git pull origin "$BASE_BRANCH"
        
        # Create release branch from develop
        git checkout -b "$RELEASE_BRANCH"
        
        # Set release version (no -SNAPSHOT)
        if [ -f "pom.xml" ]; then
          echo "Detected Maven project"
          mvn -q versions:set -DnewVersion="$VERSION" -DgenerateBackupPoms=false
        elif [ -f "gradle.properties" ]; then
          echo "Detected Gradle project"
          sed -i.bak "s/^version=.*/version=$VERSION/" gradle.properties
          rm -f gradle.properties.bak
        else
          echo "WARNING: No build tool detected (pom.xml or gradle.properties)"
        fi
        
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "chore(release): prepare release $VERSION"
        else
          echo "No changes to commit"
        fi
        git push -u origin "$RELEASE_BRANCH"
        
        echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
        echo "release_version=$VERSION" >> $GITHUB_OUTPUT
        echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT