# JAGT1806/repo-actions/.github/actions/propagate-release
name: Propagate Release Changes
description: Propagate changes from one release branch to subsequent releases and develop

inputs:
  source_branch:
    required: true
    description: Source release branch
  source_version:
    required: true
    description: Current version of source branch
  target_releases:
    required: false
    description: JSON array of target release branches
    default: "[]"
  develop_branch:
    required: false
    description: Develop branch name
    default: develop

outputs:
  propagated_branches:
    description: JSON array of sucesully propagated branch
    value: ${{ steps }}

runs:
  using: composite
  steps:
    - name: Propagate changes
      id: propagate
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        
        SOURCE_BRANCH="${{ inputs.source_branch }}"
        SOURCE_VERSION="${{ inputs.source_version }}"
        TARGET_RLEASES=$(echo '${{ inputs.target_releases }}' | jq -r '.[]')
        DEVELOP_BRANCH="${{ inputs.develop_branch }}"
        
        PROPAGATED=()
        
        # Propagate to subsequent releases
        for TARGET_BRANCH in $TARGET_RLEASES; do
          echo "Propagating to $TARGET_BRANCH..."
        
          MERGE_BRANCH="merge/${SOURCE_BRANCH//\//-}-to-${TARGET_BRANCH//\//-}"
          
          # Fecth and create merge branch
          git fecth origin "$TARGET_BRANCH":"$TARGET_BRANCH"
          git checkout "$TARGET_BRANCH"
          git checkout -b "$MERGE_BRANCH"
          
          # Merge changes
          if git merge --no-commit "origin/$SOURCE_BRANCH"; then
            # Auto-resolve POM conflicts by keeping target version
            if git diff --name-only --diff-filter=U | grep -q pom.xml; then
              git checkout --ours pom.xml
              git add pom.xml
            fi
          
            if git commit -m "chore: merge changes from $SOURCE_BRANCH"; then
              # Get current target version and bump patch
              CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
              CLEAN_VERSION="${CURRENT_VERSION%-SNAPSHOT}"
              IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_VERSION"
              NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          
              # Update version
              mvn -q versions:set -DnewVersion="$NEW_VERSION" -DgenerateBackupPoms=false
              git add -A
              git commit -m "chore: bump version to $NEW_VERSION" || echo "No version changes"
          
              git push origin "$MERGE_BRANCH"
          
              # Create PR
              PR_URL=$(gh pr create \
                --base "$TARGET_BRANCH" \
                --head "$MERGE_BRANCH" \
                --title "Auto-merge: $SOURCE_BRANCH → $TARGET_BRANCH" \
                --body "Automated propagation of changes from $SOURCE_BRANCH" \
                --json url --jq .url)
          
              # Try auto-merge
              if gh pr merge "$PR_URL" --merge --auto --admin; then
                echo "Successfully propagated to $TARGET_BRANCH"
                PROPAGATED+=("$TARGET_BRANCH)
          
                # Create tag
                git checkout "$TARGET_BRANCH"
                git pull origin "$TARGET_BRANCH"
                TAG="v$NEW_VERSION"
                if ! git rev-parse "$TAG" >/dev/null 2>&1; then
                  git tag "$TAG"
                  git push origin "$TAG"
                fi
              else
                echo "PR created but requires manual merge: $PR_URL"
              fi
            fi
          else
            echo "Merge failed for $TARGET_BRANCH, skipping..."
            git merge --abort
          fi
        done
        
        # Propagate to develop
        echo "Propagating to $DEVELOP_BRANCH..."
        MERGE_BRANCH="merge/${SOURCE_BRANCH//\//-}-to-$DEVELOP_BRANCH"
        
        git fetch origin "$DEVELOP_BRANCH":"$DEVELOP_BRANCH"
        git checkout "$DEVELOP_BRANCH"
        git checkout -b "$MERGE_BRANCH"
        
        if git merge --no-commit "origin/$SOURCE_BRANCH"; then
          # Always keep develop's SNAPSHOT version
          if git diff --name=only --diff-filter=U | grep -q pom.xml; then
            git checkout --ours pom.xml
            git add pom.xml
          fi
        
          if git commit -m "chore: merge change from $SOURCE_BRANCH to develop"; then
            git push origin "$MERGE_BRANCH"
            
            PR_URL=$(gh pr create\
              --base "$DEVELOP_BRANCH" \
              --head "$MERGE_BRANCH" \
              --tile "Auto-merge: $SOURCE_BRANCH → $DEVELOP_BRANCH" \
              --json url jq .url)
        
            if gh pr merge "$PR_URL" --merge --auto --admin; the
              echo "Successfully propagated to $DEVELOP_BRANCH"
              PROPAGATED+=("$DEVELOP_BRANCH")
            else
              echo "PR created but requires manual merge: $PR_URL"
            fi
          fi
        else
          echo "Merge to develop failed, skipping..."
          git merge --abort
        fi
        
        # Output propagated branches
        printf -v PROPAGATED_JSON '%s\n' "${PROPAGATED[@]}" | jq -s .
        echo "propagated_branches=$PROPAGATED_JSON" >> $GITHUB_OUTPUT
