# JAGT1806/repo-actions/.github/actions/propagate-release
name: Propagate Release Changes
description: Propagate changes from one release branch to another branch

inputs:
  from_branch:
    required: true
    description: Source branch (release branch)
  to_branch:
    required: true
    description: Target branch (next release or develop)
  packaging:
    required: false
    description: Build tool (maven|gradle)
    default: maven
  github_token:
    required: true
    description: Github Token

outputs:
  merged:
    description: Whether the propagation was successful
    value: ${{ steps.propagate.outputs.merged }}
  pr_url:
    description: URL of created PR
    value: ${{ steps.propagate.outputs.pr_url }}

runs:
  using: composite
  steps:
    - name: Propagate changes
      id: propagate
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        
        FROM_BRANCH="${{ inputs.from_branch }}"
        TO_BRANCH="${{ inputs.to_branch }}"
        PACKAGING="${{ inputs.packaging }}"
        
        echo "Propagating from $FROM_BRANCH to $TO_BRANCH"
        
        # Create merge branch
        MERGE_BRANCH="merge/${FROM_BRANCH//\//-}-to-${TO_BRANCH//\//-}"
        echo "Merge branch: $MERGE_BRANCH"
        
        # Fetch latest changes
        git fetch origin
        git checkout -b "$MERGE_BRANCH" "origin/$TO_BRANCH"
        git push --set-upstream origin "$MERGE_BRANCH"
        
        # Merge changes
        if git merge --no-edit "origin/$FROM_BRANCH"; then
          echo "Merge successful"
        
          # Resolve version conflicts based on packaging
          if [ "$PACKAGING" = "maven" ] && [ -f "pom.xml" ]; then
            if git diff --name-only --diff-filter=U | grep -q pom.xml; then
              echo "Resolving Maven version conflict"
              git checkout --ours pom.xml
              git add pom.xml
            fi
          elif [ "$PACKAGING" = "gradle" ]; then
            # Check for gradle.properties conflicts
            if git diff --name-only --diff-filter=U | grep -q gradle.properties; then
              echo "Resolving Gradle version conflict"
              git checkout --ours gradle.properties
              git add gradle.properties
            fi
            # Check for build.gradle conflicts
            if git diff --name-only --diff-filter=U | grep -q build.gradle; then
              echo "Resolving build.gradle conflict"
              git checkout --ours build.gradle
              git add build.gradle
            fi
          fi
        
          # Commit if there were resolved conflicts
          if ! git diff --cached --quiet; then
            git commit --no-edit
          fi
        
          git push origin "$MERGE_BRANCH"
        
          # Create PR
          PR_URL=$(gh pr create \
            --base "$TO_BRANCH" \
            --head "$MERGE_BRANCH" \
            --title "Auto-merge: $FROM_BRANCH → $TO_BRANCH" \
            --body "Automated propagation of changes from $FROM_BRANCH" \
            --json url --jq .url)
        
          echo "PR created: $PR_URL"
          PR_NUMBER=$(basename "$PR_URL")
        
          # Wait for PR to be ready for merge
          echo "Waiting for PR to be mergeable..."
          for i in {1..10}; do
            MERGEABLE=$(gh pr view "$PR_NUMBER" --json mergeable --jq .mergeable)
            if [ "$MERGEABLE" != "UNKNOWN" ]; then
              break
            fi
            sleep 2
          done
        
          if [ "$MERGEABLE" = "MERGEABLE" ]; then
            echo "Auto-merging PR..."
            gh pr merge "$PR_NUMBER" --merge --delete-branch --admin
            echo "merged=true" >> $GITHUB_OUTPUT
          else
            echo "PR not mergeable. Status: $MERGEABLE"
            echo "merged=false" >> $GITHUB_OUTPUT
          fi
        
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        
        else
          echo "Merge failed, aborting..."
          git merge --abort
          echo "merged=false" >> $GITHUB_OUTPUT
          echo "pr_url=" >> $GITHUB_OUTPUT
        fi
